### ISSUE TITLE
Ændre click handler fra popup til event/andet

### ISSUE THREAD

**Issue by Fredemb** [SDFIdk/okapi#102]
Fetaure-request:
Mulighed for at håndtere klik på anden måde end ved at vise popup.
Evt. emit et event til EventBus, som man kan lytte på, og køre sin egen logik.

- [x] Mulighed for at disable popup
- [ ] Mulighed for at håndtere klik-event på anden måde

**Comment by Fredemb** [comment]
Det viser sig ved nærmere nærlæsning at det allerede er muligt at disable popup på markørerne, ved at sætte "data-show-popup" til "false".
Dog disables click tilsyneladende helt hvis man gør det, så det er ikke en løsning på problemet.

**Comment by Gebuz** [comment]
Som et midlertidigt work around kan du bruge Openlayers egen click event direkte:
```
map.olMap.on('singleclick', function (evt) {
  const feature = map.olMap.forEachFeatureAtPixel(evt.pixel,
    function (feature) {
      return feature
    })
})
```
