### ISSUE TITLE
Eliminér warning: Set "willReadFrequently" attribute on canvas to true

### ISSUE THREAD

**Issue by Fredemb** [SDFIdk/okapi#104]
Jeg får følgende warning i konsollen hver gang jeg interagerer med kortet i min web-app:

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

**Comment by Gebuz** [comment]
Jeg får ikke nogen warnings i min konsol så har brug for mere info. 
Får du også fejlen på demo siderne? f.eks. https://okapi.dataforsyningen.dk/examples/advanced.html 
Ellers har jeg nok brug for et kode eksempel for at kunne hjælpe.
Hvis du også får fejlen på demo siderne:
Hvilken browser bruger du?
Bruger du den nyeste version af Okapi?

**Comment by Fredemb** [comment]
Jeg får også (men i mindre grad) warningen på disse demoer:
https://okapi.dataforsyningen.dk/examples/markers-advanced.html
https://okapi.dataforsyningen.dk/examples/tooltip.html

Den trigges tilsyneladende af mouseover-event på markørerne, og trigges oftere jo flere markører der er på kortet
Jeg bruger Google Chrome.

**Comment by Gebuz** [comment]
Tak, jeg kigger på det.

**Comment by Gebuz** [comment]
Ser ud til at det kun sker på markers hvor tooltip er slået til, så det er formentlig den her listener der er synderen:
https://github.com/SDFIdk/okapi/blob/147a2923f567cb8fba19b899b0600aed3ee5ee10/src/control/markers/CreateMarkerTooltip.js#L78
