### ISSUE TITLE
TypeError i @dataforsyningen\okapi\dist\index.js

### ISSUE THREAD

**Issue by Fredemb** [SDFIdk/okapi#112]
Jeg får følgende fejl når jeg bygger min kode til produktion:

`Uncaught TypeError: Super constructor null of bn is not a constructor at new bn (index.js:5:35833)`

Jeg bruger npm pakken [herfra](https://www.npmjs.com/package/@dataforsyningen/okapi?activeTab=readme)
Underligt nok giver det ikke problemer når jeg tester på NODE_ENV "development", fejlen kommer kun på NODE_ENV "production"

Kan i hjælpe mig med at troubleshoote?

**Comment by iamfrank** [comment]
@Fredemb Bruger du tilfældigvis Vite til at bygge applikation med? Vite bruger forskellige setups til dev og prod, og de skal konfigureres hver for sig.

**Comment by Fredemb** [comment]
@iamfrank Det er en Vue2 applikation, og jeg bruger umiddelbart ikke Vite til noget, nej - Men jeg kunne sagtens forestille mig at det var et lignende issue - det er bare første gang jeg støder ind i den slags problem, så jeg har ikke erfaring med at debugge det endnu. 
I development synes jeg jo ikke at jeg gjorde andet end at installere npm pakken, og så importere og kalde "Initialize", som beskrevet i dokumentationen, så jeg synes jo ikke umiddelbart at der er noget setup jeg har lavet til den...

Hvad for noget setup tænker du konkret der skal laves?

**Comment by iamfrank** [comment]
@Fredemb Det var bare for at udelukke Vite som fejlkilde. Hvis du bruger Vue2, er det nok ikke relevant. Vi kigger på sagen.

**Comment by Gebuz** [comment]
Jeg har replikeret fejlen på en af vores applikationer der bruger Vue og Webpack. Grunden til at det virker i dev og ikke prod ser ud til at være pga. at det bliver minified i prod. Den kommer formentlig til at ødelægge nogle klasse eller variabel navne når den minifier noget der allerede er minified. Vi kigger på at få det fixet.

**Comment by Gebuz** [comment]
Det er desværre ikke lykkedes os at finde en løsning eller workaround endnu. Jeg har prøvet en hel masse forskellige ting med webpack, men den virker ret insisterende på at fjerne nogle imports den ikke burde fjerne når den bygger til prod lige meget hvilke instillinger jeg bruger. Har også eksperimenteret med at bygge okapi på andre måder, men det har heller ikke løst problemet. Vi skal nok melde tilbage når vi finder en løsning.

**Comment by Gebuz** [comment]
Dette skulle være fikset i den nyeste release. Meld gerne tilbage om det virker.

**Comment by Fredemb** [comment]
> Dette skulle være fikset i den nyeste release. Meld gerne tilbage om det virker.

Det virker nu ja :-)
