### ISSUE TITLE
https://okapi.dataforsyningen.dk/lib/okapi-1.9.0.min.js giver 404

### ISSUE THREAD

**Issue by LauridsBygst** [SDFIdk/okapi#115]
Dette link: https://okapi.dataforsyningen.dk/lib/okapi-1.9.0.min.js giver 404

https://okapi.dataforsyningen.dk/lib/okapi-1.9.0.min.js

**Comment by iamfrank** [comment]
Vi arbejder på at opdatere vores CDN. Indtil da kan man downloade filen fra 
https://raw.githubusercontent.com/SDFIdk/okapi/master/lib/%40dataforsyningen/okapi-1.9.0.min.js

**Comment by iamfrank** [comment]
@LauridsBygst Man kan nu hente seneste version af Okapi JS på https://cdn.jsdelivr.net/npm/@dataforsyningen/okapi@2.0.0
(Værk opmærksom på major update.)

Version 1.9.0 er tilgængelig på https://cdn.jsdelivr.net/npm/@dataforsyningen/okapi@1.9.0/lib/@dataforsyningen/okapi-1.9.0.min.js

README på https://github.com/SDFIdk/okapi er opdateret.
