### ISSUE TITLE
What's the point of the the token ?

### ISSUE THREAD

**Issue by jektvik** [SDFIdk/okapi#117]
In all examples, the credential token is attached to the public web page source code. It's accessible to everyone. What purpose does it serve ?
Are there any services recommended to facilitate proxying the requests and decorate the token on the backend proxy instead ?

**Comment by Gebuz** [comment]
The token is used to identify the application or user making the call to our backends. We strongly recommend that you create your own token, as the owner of the token might delete it or change its permissions at any point. That also applies to the token used on the example pages. You can create your own token here: https://dataforsyningen.dk/user#token .
