### ISSUE TITLE
Overlappende markører

### ISSUE THREAD

**Issue by EV-soft** [SDFIdk/okapi#32]
Jeg har et problem med flere markører på samme adresse.
Kun en markør er synlig og klikbar.
Er det muligt at indsætte markører med f.eks. multipla af 30 graders rotation omkring indsætningspunktet?
En alternativ løsning kunne være at 2. og efterfølgende markører placeres med en offset af x-koordinaten.

**Comment by rasmustoender** [comment]
Vi er lidt i tvivl om hvad der menes med problemet. Under hvilket eksempel oplever du dette sker? Som udgangspunkt tilbyder vi med OKAPI en værktøjskasse, hvor det er muligt at videreudvikle og implementere egne brugerdefinerede løsninger. Dette vil vi som udgangspunkt opfordre til at man gør.

**Comment by EV-soft** [comment]
Det jeg savner er muligheden for at rotere markører, så de ikke dækker for hinanden, når der er flere placeret på samme koordinat. Eksempelvis: en pakke til en beboer på 1. sal samt en anden pakke til en beboer på 3. sal.
Hvor finder jeg værktøjskassen ?

**Comment by DocDemar** [comment]
@EV-soft  - er det en konkret løsning du arbejder på hvor du har behov for denne feature?

**Comment by EV-soft** [comment]
Ja - men jeg mener det kan være generelt gavnligt, at det er muligt.

**Comment by DocDemar** [comment]
Det er ikke muligt for os at få denne feature med i den kommende release som er lige på trapperne
@EV-soft  - hvis du har mulighed for at lave en PR på denne feature så kan den komme ud hurtigt
Ellers må den nok vente til en kommende release

**Comment by EV-soft** [comment]
Hvor finder jeg OKAPI værktøjskassen ?

**Comment by DocDemar** [comment]
> Hvor finder jeg OKAPI værktøjskassen ?

Den kode som udgør OKAPI er det der bliver refereret til som værktøjskassen
Der er ikke yderligere værktøjer
beklager misforståelsen
