### ISSUE TITLE
 onmozfullscreenchange warning in Firefox

### ISSUE THREAD

**Issue by EV-soft** [SDFIdk/okapi#34]
okapi udløser warning: onmozfullscreenchange er forældet. 
Firefox v. 87.0 (64-bit)
Source: okapi.kortforsyningen.dk/lib/okapi-1.3.min.js (:13:10896)

**Comment by iamfrank** [comment]
Næste release af okapi vil sandsynligvis ikke udløse denne warning, da vi opgraderer openlayers.

**Comment by Gebuz** [comment]
Closing as it was fixed when the Openlayers version was updated.
