### ISSUE TITLE
How to add/remove markers dynamically?

### ISSUE THREAD

**Issue by rfonovicell** [SDFIdk/okapi#55]
Hi there, I see you were planning to update the examples/documentation with how to add/remove new markers to a map dynamically: https://github.com/SDFIdk/okapi/issues/10

I couldn't find a way to "refresh" the map and read new markers that I add to the page, on the readme file nor on the examples. Can you help me out?

**Comment by iamfrank** [comment]
@rfonovicell Sorry about the late response but we are looking into making a solution for adding/removing markers dynamically at this time.

We have some different solutions in mind and would like your feedback on what would best suit your use case.

We could do something like this:
- There could be a function like `okapi.refresh()`. 
- When `okapi.refresh()` is called, _all markers presently available_ in the HTML document will be created as map markers.
- All old markers on the map will be overwritten with the new set of markers.

So the workflow would be:
1. Add marker HTML
2. `okapi.refresh()`
3. Experience updated map markers

How would this work in your case?

**Comment by iamfrank** [comment]
Proposed fix has been merged into `dev` branch with #91 
Pending next release

**Comment by iamfrank** [comment]
Ready for release
