### ISSUE TITLE
bump OL to latest version

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/okapi#63]
opgrader Open Layers

**Comment by iamfrank** [comment]
I den forbindelse vil jeg nævne, at jeg har haft blandet success med at opgradere andre projekter til OpenLayers 7.0.0.
Det har drejet sig om formodede webGL quirks i forbindelse med projektering af skråfotos.

Jeg vil anbefale, at man tester systemet godt igennem i forbindelse med en opdatering.

**Comment by iamfrank** [comment]
Vi skal have ryddet nogle transpilation-issues af vejen, før vi kan opgradere til ol 7. 
@rasmustoender , @gebuz og jeg er blevet enige om at lave en major release, hvor vi dropper support for gamle browsere. Det betyder også, at vi kan fjerne babel og transpilesteppet. Som igen burde gøre det muligt at opgradere til ol 7.
