### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by iamfrank** [SDFIdk/okapi#66]
Dependabot alerts should be reviewed and dependencies updated accordingly.

**Comment by utsav00** [comment]
Hey, can I take this up?

**Comment by iamfrank** [comment]
I am not sure what 'up' means in this context. 
We are currently working on an updated release, so it should be out soon-ish.

**Comment by utsav00** [comment]
I meant to ask if I can work on this since it is already assigned to you.

**Comment by iamfrank** [comment]
No need. We'll push updates to `master` branch by the end of the day.

**Comment by iamfrank** [comment]
Upgrades have been pushed to `dev` branch.
Push to `master` branch is still pending.

**Comment by iamfrank** [comment]
New release scheduled for late November

**Comment by iamfrank** [comment]
Fixed on master branch
