### ISSUE TITLE
tilføj flere baggrundskort

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/okapi#70]
- [x] kommunikation
 - [x] natur og friluft (nf)
 - [x] opdater kort ikoner

**Comment by elvios** [comment]
wms:kommunikation  (findes ikke paa webtjenestelisten, men den findes altsaa)
wms:natur_friluftskort

**Comment by Gebuz** [comment]
folderen med ikoner: https://github.com/SDFIdk/okapi/tree/master/src/control/images

**Comment by rasmustoender** [comment]
Alle issues er nu klaret. Nye ikoner kan findes under eksemplet: '/examples/datafordeler.html'
